apiVersion: apps/v1
kind: Deployment
metadata:
  name: membership
  labels:
    app: membership
spec:
  selector:
    matchLabels:
      app: membership
  template:
    metadata:
      labels:
        app: membership
    spec:
      containers:
      - name: membership
        image: dev/membership:dev
        ports:
        - containerPort: 8080
        env:
        - name: PRICING_SERVICE_HOST
          value: pricing:8080
        - name: OTEL_SERVICE_NAME
          value: membership
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://jaeger.tracing:4317
  