apiVersion: odigos.io/v1alpha1
kind: Destination
metadata:
  name: prometheus-rw
  namespace: odigos-system
spec:
  data:
    PROMETHEUS_REMOTEWRITE_URL: http://prometheus.prometheus:9090/api/v1/write
  destinationName: "prometheus remote write"
  signals:
  - METRICS
  sourceSelector:
    dataStreams:
    - default
  type: prometheus
  metricsSettings:
    spanMetricsEnabled: true
